### ISSUE TITLE
Plans to update PyPI?

### ISSUE THREAD

**Issue by kylegibson** [scalyr/scalyr-agent-2#113]
Last released version on PyPI was 2.0.27 on Jun 3, 2017. I would prefer to be able to install the latest version from PyPI rather than apt.

**Comment by czerwingithub** [comment]
Our apologies, it looks like our process missed this.

We are releasing a new version of the agent later today (maybe tomorrow
morning).  We will be sure to update PyPI then and fix our tools to make
sure it is done in the future.

**Comment by czerwingithub** [comment]
@kylegibson I'm sorry this took so long, but we just published a new relesae (2.0.37) to PyPi.  We will continue to push to PyPi going forward.  Thank you for your patience with this.
