### ISSUE TITLE
Ability to ignore k8s labels

### ISSUE THREAD

**Issue by tr3mor** [scalyr/scalyr-agent-2#1213]
Hi,

Currently k8s Scalyr agent adds all labels of a pod and controller to pod logs. While this is a valuable feature, on a larger scale it can introduce noise from unnecessary labels and increase the volume of ingested data. Some of these labels may not be useful as log labels, such as labels used for configuring other tools.

It would be great to have a configuration option for the Kubernetes monitor that allows users to specify a list of labels to be ignored and not added to logs. This feature could help users get rid of irrelevant labels from their logs.

**Comment by weilliu** [comment]
Sounds good, I will create a feature request for us to track internally.
