### ISSUE TITLE
Never captures really short live jobs

### ISSUE THREAD

**Issue by tr3mor** [scalyr/scalyr-agent-2#1231]
Hello,
In one of the latest releases the following part was changed:
https://github.com/scalyr/scalyr-agent-2/blob/1245df039d0402d7b6a1b13536e64203d19c815f/scalyr_agent/builtin_monitors/kubernetes_monitor.py#L2277-L2295
Following this update, any job completed in beetwen the Scalyr checks will not be included in the log collection. The API will return a 404 error for these pods, resulting in their exclusion from the log collection. This scenario is frequently observed for our Argo workflows.
Instead of always discarding such pods, I would suggest fallback to global config (env SCALYR_K8S_INCLUDE_ALL_CONTAINERS ) to determine if pod's logs should be collected or not.
I think that if you include all pods by default, you expect it as default behavior and vice versa.
If not, I would like to understand what is the better way to handle such cases (we already have container_check_interval set to 2sec).

**Comment by weilliu** [comment]
@tr3mor Apologies for the delayed response. The engineering confirms the issue and we'll implement a fix in the future agent version to address the problem.

**Comment by weilliu** [comment]
The fix will be deployed to the next agent release

**Comment by jmakar-s1** [comment]
This is fixed by this commit and is included in the 2.2.13 release: https://github.com/scalyr/scalyr-agent-2/commit/395ad4e8059602d5fc91eb3cd23d77cb76040bb5
