### ISSUE TITLE
AttributeError: 'module' object has no attribute '_strptime_time' and missing logs

### ISSUE THREAD

**Issue by sohan** [scalyr/scalyr-agent-2#139]
Hi, we're running the Scalyr agent on Kubernetes. We noticed that the logs for some, but not all, of our deployments are not showing up in Scalyr with k8s-cluster and k8s-deployment tags. However, we _do_ see the logs for those deployments attributed to the Scalyr agents' /var/log files.

That is, we're seeing logs here:
![image](https://user-images.githubusercontent.com/911977/54000912-28175780-40fe-11e9-95b7-665e9b145473.png)

But not in the "Logs" tab in the UI, nor when we search for `$k8s-cluster="clustername"`. We haven't noticed a pattern for which deployments this affects.

We're also consistently seeing errors in our scalyr-agent-2 pods:

```
$ kubectl logs -n default -l app=scalyr-agent-2

Exception in thread metric thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/builtin_monitors/kubernetes_monitor.py", line 1978, in run
    tm = time.strptime( "2016-08-29", "%Y-%m-%d" )
AttributeError: 'module' object has no attribute '_strptime_time'
```

Are these errors relevant? Any other ideas for why logs might be attributed to the agent but not our kubernetes deployment?

Also maybe relevant: we customized our agent-d and agent.json to disable collecting docker and k8s metrics:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: scalyr-config-agent-d
data:
  api-key.json: |+
    {
        import_vars: [ "SCALYR_API_KEY" ],
        api_key: "$SCALYR_API_KEY"
    }

  docker.json: |+
    {
      "monitors":[
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_monitor",
          "report_k8s_metrics": false,
          "report_container_metrics": false
        }
      ]
    }

  scalyr-server.json: |+
    {
      "import_vars": [ { "var": "SCALYR_SERVER", "default": "https://agent.scalyr.com" } ],
      "scalyr_server": "$SCALYR_SERVER"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scalyr-config-agent-json
data:
  agent.json: |+
    // Configuration for the Scalyr Agent while running on Kubernetes. For help:
    //
    // https://www.scalyr.com/help/scalyr-agent-2

    {
      // Note:  It is assumed that another file such as `agent.d/api-key.json`
      // will contain the api key for the user's Scalyr account.
      implicit_metric_monitor: false,
      implicit_agent_process_metrics_monitor: false,
      monitors: [{
        module: "scalyr_agent.builtin_monitors.docker_monitor",
        report_container_metrics: false
      }]
    }
```

**Comment by jmullady** [comment]
On the logs home page, do you not see the k8s cluster?  
Let's try installing the product again, and see if the k8s shows up.  
1. Create a Secret that contains your Write Logs API key. You can find your API key here under "Logs Access Keys". Make sure the key has "write" access.

kubectl create secret generic scalyr-api-key --from-literal=scalyr-api-key="0cegDcV4UQwZ2ST3nYrJ4GCEcq__6l/JVUjhFtB8mLYA-"
2. Create a ConfigMap that defines your cluster name.

kubectl create configmap scalyr-config --from-literal=k8s_cluster=<your_k8s_cluster_name> 
3. Create a service account that gives the DaemonSet the required privileges to access the Kubernetes API.

kubectl create -f https://raw.githubusercontent.com/scalyr/scalyr-agent-2/release/k8s/scalyr-service-account.yaml
4. Install the new Scalyr k8s DaemonSet.

kubectl create -f https://raw.githubusercontent.com/scalyr/scalyr-agent-2/release/k8s/scalyr-agent-2.yaml

**Comment by jmullady** [comment]
https://www.scalyr.com/help/install-agent-kubernetes

**Comment by sohan** [comment]
Thanks for your reply! Sorry I wasn't clear -- the issue was that _some_ of my k8s deployments did not show up on the logs home page. I did see my k8s cluster and _most_ deployments there.

Thanks for the idea to try reinstalling the project and re-read the docs. I modified my docker.json and agent.json configs again, and everything seems to work now. The `AttributeError: 'module' object has no attribute '_strptime_time'` errors disappeared as well:

docker.json:
```
    {
      "monitors": [
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_monitor",
          "include_deployment_info": true,
          "k8s_use_v2_attributes": true,
          "report_k8s_metrics": false,
          "report_container_metrics": false
        }
      ]
    }
```

agent.json:
```
    {
      // Note:  It is assumed that another file such as `agent.d/api-key.json`
      // will contain the api key for the user's Scalyr account.
      implicit_metric_monitor: false,
      implicit_agent_process_metrics_monitor: false,
    }
```

(I had modified these configs originally, because I wanted to disable collecting k8s and docker metrics, which had high volume and little value to us. It looks like I just botched the config)
