### ISSUE TITLE
Memory leak/High CPU Load

### ISSUE THREAD

**Issue by bheads** [scalyr/scalyr-agent-2#215]
Looks like there is a memory leak/high cpu load in 2.0.47, it was bad enough to bring our product site down after about 10 days of running. We had some other servers running 2.0.45 without this issue.
We notices that 2.0.45 runs around with 19mb, 2.0.47 starts off using 19mb but after a week it was using 120mb.

Same aws instance and site code:

ver. 2.0.47
![image](https://user-images.githubusercontent.com/819068/58106549-48f83080-7bb6-11e9-906f-867f7fc6f31a.png)

ver. 2.0.45
![image](https://user-images.githubusercontent.com/819068/58173966-bfef0100-7c6a-11e9-851e-9b57d971e949.png)

**Comment by bheads** [comment]
Here are some cpu charts borken down by process, the scalyr agent is the python process:

2.0.47
![scalyr_2 0 47](https://user-images.githubusercontent.com/819068/58176132-9f757580-7c6f-11e9-9e84-d607324aba0d.png)

2.0.45
![scalyr_2 0 45](https://user-images.githubusercontent.com/819068/58176165-b4ea9f80-7c6f-11e9-94a9-eb95cd839132.png)

**Comment by imron** [comment]
Thanks for that.  We are investigating this as a high priority.

**Comment by echee2** [comment]
@bheads thank you very much for reporting this.

We believe we've found the leak and will be posting a new release asap.

(The leak was introduced in 2.0.47.)

**Comment by echee2** [comment]
@bheads we've published a 2.0.48 bugfix release that hopefully fixes this. (We're pretty confident it does but please do let us know if you continue to see problems).

Again, thank you for notifying us and our sincere apologies for any inconvenience.

**Comment by bheads** [comment]
Wow, your team is fast!  I didnt even get to reply to your ask about configs!

**Comment by bheads** [comment]
I deployed the 2.0.48 agent into our testing environment, I will watch it for a few days and let you know.  Thanks for the fast turn around.

**Comment by echee2** [comment]
Thank you, and our apologies again. We will be auditing our validation process to examine how this slipped through.

**Comment by echee2** [comment]
@bheads I'm going to close this issue for now but please feel free to open a new ticket if you have further problems. Thank you.
