### ISSUE TITLE
Use different parser for syslog monitor

### ISSUE THREAD

**Issue by czerwingithub** [scalyr/scalyr-agent-2#24]
Right now, the parser for the syslog monitor's log is "systemLog".  Let's change this to something unique just for the syslog monitor so that we can change it how it is parsed server side in Scalyr.  Let's just change it to "syslogServer"

**Comment by imron** [comment]
Done, and pushed to the syslog branch of my repo.

**Comment by steve-scalyr** [comment]
This name is user-visible, so we should try to make it as meaningful as
possible. How about "agentSyslog"?

It occurs to me, at some point we're going to need to come up with a better
mechanism for handling syslog files. For instance, suppose a customer is
using syslog to import a web access log and a MySQL slow query log. They're
going to want to assign different parsers to those logs... and they're
going to want them to show up as separate logs in the Overview page. But
let's get the basic syslog support out in the field before we start
wrestling with this.

Steve

**Comment by imron** [comment]
How much of that is possible to do on the backend?

Syslog messages should generally contain the name of the process that generated them (or a user defined tag) so it should be possible to split them out.

We can do that on the client too, it just depends on whether we'd be doubling up on the parsing that might be taking place on the server anyway.

**Comment by steve-scalyr** [comment]
Unfortunately this doesn't fall out of the parsing we're doing on the
server. Our server-side parsing doesn't kick in until we know which parser
to use, and we need this step to even decide which parser to use.

A side question. In practice, how hard is it going to be to tell which log
file (and host) a given syslog message originated in? Is there any
standardization to this? I'm guessing not, in which case we'd probably need
to allow the user to specify regular expressions to extract filename and
hostname fields (if any) from their syslog feed. Leaving aside, for the
moment, the question of whether this is done in the agent or on the backend.

Steve

**Comment by imron** [comment]
There is standardization of sorts, as in there is an [RFC](https://tools.ietf.org/html/rfc5424) (and also an [older one](https://tools.ietf.org/html/rfc3164) too).  I'm not sure how well those are followed in the wild.  

Do you have any sample syslog message data available (I can generate my own, but was just wondering if you had any real world data on hand for testing).

Anyway, if we get a well formatted message it should be relatively easy to parse out the originating process and host (syslog messages don't contain a filename).  

Either way, it probably wouldn't be too difficult to allow the user to specify a regex to pull out that if needed.

We could then add an option to the syslog config, which would be a dict mapping process names to parsers and optionally filenames.

**Comment by steve-scalyr** [comment]
A dictionary mapping process names to parsers and optional filenames sounds
like a good idea. By default we could use the process name as the filename.
For some users we may eventually find that we need to do something more
flexible, but it's hard to anticipate so I like the idea of starting with
something simple and iterating as needed.

I don't have any real-world data to pass along unfortunately.

Steve

**Comment by czerwingithub** [comment]
I know we don't want to get too much into whether we should do this mapping
server side or in the agent, but just I want to make one point.  (And taken
for granted that we are going to implement it on the agent for now to help
get this moving).

I think long term, we will want to do this mapping and other similar
operations server-side.  After all, we are going to offer a Scalyr hosted
syslog receiver at some point, (something like https://syslog.scalyr.com),
and we are going to have to solve the same problems for that as the
agent-based syslog receiver.  We will be required to go with a server-side
solution for that.  Additionally, I think as we move to support docker
better and better, we are going to find it is easier to host configuration
server side.  After all, it seems to me the easiest docker experience is
just giving them a commandline where they can set the api key and server
host name... having them modify the configuration file in that container
seems like it might not be scalable in a docker scenario.  Of course, we
don't have enough experience with customers using docker to know for sure.

**Comment by imron** [comment]
>A dictionary mapping process names to parsers and optional filenames sounds
like a good idea.

Ok, I'll maybe also allow providing a custom regex in to the mix also, defaulting to manual parsing based on the RFC if none is provided.

>After all, we are going to offer a Scalyr hosted
syslog receiver at some point, (something like https://syslog.scalyr.com),
and we are going to have to solve the same problems for that as the
agent-based syslog receiver

If we are running that on Scalyr servers though, we could use an existing off the shelf syslog server, which can probably do this already.

>After all, it seems to me the easiest docker experience is
just giving them a commandline where they can set the api key and server
host name... having them modify the configuration file in that container
seems like it might not be scalable in a docker scenario

It strikes me that with the way docker allows you to build your own images off of base images, and also provides tools for diffing and updating, we could ship a default scalyr container, clients could then alter their configuration to set keys, host names and other settings, save/commit the new image, and then use that image for deploying containers.

It's only slightly more work for them than running a command to set their Scalyr keys and server host names, and it's probably safe to assume that the person doing deployment via docker is going to be familiar with that process.

**Comment by steve-scalyr** [comment]
One advantage of client-based configuration is that you can do it as part
of the same process you're using to provision / deploy / configure the rest
of the software on that client. If we move to server-based configuration,
we'll need to preserve some way of driving the configuration from the
client (perhaps via an API). A few scenarios to consider:

1. Already today, I believe we have customers using Scalyr on auto-scaling
server pools. Their server template includes an agent configuration file,
so when the autoscaler adds a new server, it comes up already configured
and reporting data.

2. A user might use Chef or Puppet or whatever to add or remove an
application from a server. They'll likely want to update the agent
configuration at the same time. Chef or Puppet can easily add or remove a
modular configuration file to do this.

Steve

**Comment by arohter** [comment]
We use syslog as a generic transport mechanism to ship logs through our platform.  It's fairly robust, flexible and commonly supported (we currently route into an ELK cluster).  As such, our syslog lines consist of a standard header - timestamp, host, process (analogous to filename) - and several different message/body formats (ad hoc strings/words, key=value pairs, json blobs, etc).  
Thus, we can't really use the simple built-in systemLog parser, since we also need to parse the message body as well.  So we end up making customized clones of the standard parser.  For example, here's our custom "rsyslog_json" parser:
`format: "$timestamp=timestamp$ $host$ $process$\\[$procid$\\]: ${parse=json}$",`
So for our use case, having already-syslog-decoded messages for parser logic would be ideal.  We currently use different syslog Facility levels to differentiate between message/parser formats (local1 for plain, local2 for json, local3 for key-value etc).

**Comment by arohter** [comment]
As for Docker, best practices is to have your logger running **on the host**, externally aggregating the various container logs, and not inside the containers themselves (i.e. you do not run agent processes within containers).  There's already a bunch of solutions for this (https://github.com/gliderlabs/logspout being one of the best), and Docker 1.6 has now added an official "Logging Driver" mechanism, adding syslog support to the existing json output.  File logging to a shared host volume is also extremely popular.

Similarly, relying on a base scalyr container would be a no-go for us, and I suspect for most docker users.  Base images are extremely varied and their usage very particular.  Not to mention the heavy use of standardized shared images (i.e. dockerhub).  You don't want to get into the customized docker image game :)   Host-based logging makes this unnecessary anyway.

**Comment by steve-scalyr** [comment]
Thanks for this feedback! With regards to Docker: complete agreement that
running a Scalyr agent inside each container will not be the right answer
in most cases. We're currently planning to provide an agent container that
would *not* be a base container, but simply an additional container you'd
drop in alongside your other containers. Does that sound like it would work
for you?

Steve

**Comment by arohter** [comment]
Yes, I'd consider an agent container ideal, and pretty much equivalent to a "normal" agent process, and how Logspout works.  Might even consider integrating via Logspout....
https://github.com/gliderlabs/logspout
https://github.com/raychaser/logspout-http

Or borrowing from others....
https://github.com/SumoLogic/sumologic-collector-docker
https://www.sumologic.com/2014/12/11/official-docker-image-sumo-logic-collector/

**Comment by anandkumarpatel** [comment]
+1 for integration with logspout, that would make trying out scalyr with people who use docker for deployments seamless.

**Comment by jgallen23** [comment]
Has anybody been able to get logspout and scaylr agent working together?  I already have logspout configured to pass my logs to papertrail and I was hoping I could just have logspout point to the scaylr agent instead, but I can't seem to get it to work

**Comment by imron** [comment]
Are you able to provide an example of your logspout configuration?
