### ISSUE TITLE
Monitor: Cannot get metrics data of `proc.net.*`

### ISSUE THREAD

**Issue by yobo000** [scalyr/scalyr-agent-2#289]
When I viewed my logs, those metrics data named `proc.net.*` are absent. Because those hosts network interfaces are `ens*` instead of `eth`. 
I modified the default value in `scalyr_agent/builtin_monitors/linux_system_metrics.py` line 392.

```scalyr_agent/builtin_monitors/linux_system_metrics.py
        self.options.network_interface_prefixes = self._config.get('network_interface_prefixes', default="eth")
        if isinstance(self.options.network_interface_prefixes, basestring):
            self.options.network_interface_prefixes = [self.options.network_interface_prefixes]
```
to
```scalyr_agent/builtin_monitors/linux_system_metrics.py
        self.options.network_interface_prefixes = self._config.get('network_interface_prefixes', default=["eth", "ens"])
        if isinstance(self.options.network_interface_prefixes, basestring):
 
```
then it works. Is there any elegant way to do this ? Like set the `network_interface_prefixes` default value in config file?
There may have some other network interfaces like `en0`, `enp0s`, `eno1` etc.

**Comment by Uma85** [comment]
Hi yobo000

The elegant way to do it is to add the following config to the agent's monitor section. 

```
{
    module: "scalyr_agent.builtin_monitors.linux_system_metrics",
    network_interface_prefixes: "ens"
}

```
- Uma

**Comment by yobo000** [comment]
I will try it. Thanks
