### ISSUE TITLE
Please release: 2.0.21 "Querulous Quail"

### ISSUE THREAD

**Issue by zkanda** [scalyr/scalyr-agent-2#45]
Any information regarding this release? `postgres_monitor` is missing pg8000. I created this issue because it took me some time why postgres_monitor is not working.

For anyone who is experiencing the same things, just install it directly from from pip.
* `pip install pg8000`

**Comment by czerwingithub** [comment]
I'm sorry you hit the missing `pg8000` issue with the `postgres_monitor`.

I'm actually in the process of finalizing the "Querulous Quail" release now.  As long as there are no issues with the integration testing, it should be released this Thursday, Oct 6.

**Comment by czerwingithub** [comment]
Just following up.  We released "Querulous Quail" on Friday, Oct 7th.  We had an integration issue that delayed us a day.  But, your issue should be fixed now.  Thanks again for reaching out.
