### ISSUE TITLE
Journald support

### ISSUE THREAD

**Issue by mohabusama** [scalyr/scalyr-agent-2#47]
Hi,

Is there a plan for adding ``Journald`` monitor?

One workaround right now is to forward Journald to syslog (via ``ForwardToSyslog=yes``), and then configure syslog to forward to Scalyr syslog monitor. Is this the way to go or is there another recommended setup?

Thanks

**Comment by czerwingithub** [comment]
Hello -

Thanks for the question.  Yes, you can set it up as you suggested using the `syslog` monitor.  We do also have a customer-supplied `Journald` monitor that you could also try to see if it works out better for you.  Other customers have been using it with success.  (We don't have official support yet, but we are planning on doing it in the future and will probably use this plugin as the starting point).

If you are interested in trying this plugin, here are the instructions:

1.  Install the systemd python module on your system. You can find instructions at https://github.com/systemd/python-systemd.

2.   Copy the attached `journald_monitor.py.txt` file to `/usr/share/scalyr-agent-2/py/scalyr_agent/builtin_monitors/journald_monitory.py`.  NOTE, be sure to remove the `.txt` extension from the attached file first.  Github doesn't allow attached files to end in `.py`.

3. Add the highlighted clause to your list of monitors in `/etc/scalyr-agent-2/agent.json`:

``` 
    ...
    monitors: [
      {
            module: "scalyr_agent.builtin_monitors.journald_monitor"
      },
    ]
    ...
```
The agent should automatically detect this change and start running the new monitor within 60 seconds. You should start to see a log file in scalyr called `/var/log/scalyr-agent-2/journald_monitor.log`

4. Set up a parser:

- Go to https://www.scalyr.com/parser?parser=journald_monitor 
- Delete the example text, and paste in the parser definition (see attached file `journald_parser.txt`).
- Click Save Parser.

Of course, please let us know if you have any problems getting this to work.

[journald_parser.txt](https://github.com/scalyr/scalyr-agent-2/files/635107/journald_parser.txt)
[journald_monitor.py.txt](https://github.com/scalyr/scalyr-agent-2/files/635109/journald_monitor.py.txt)

**Comment by hjacobs** [comment]
@czerwingithub thanks, we will try out the `journald_monitor` and get back to you :smile:

**Comment by mohabusama** [comment]
Hi @czerwingithub 

We tested the ``Journald monitor`` and it successfully works 😃  . I have created a public Gist (with some modifications) just in case someone needs to try it out.
https://gist.github.com/mohabusama/4292076b4f68ff46e8975f9b30ae7055

Thanks

**Comment by czerwingithub** [comment]
Mohab -

Great, I'm glad it worked for you and thanks for throwing it together in a gist for us.  I hoping we can get this officially support in the near future.

-Steve
