### ISSUE TITLE
Update scalyr docker image

### ISSUE THREAD

**Issue by pierreozoux** [scalyr/scalyr-agent-2#50]
https://hub.docker.com/r/scalyr/scalyr-agent/tags/

2 years :) I think it has some vulnerabilities.
Can you update it regularly?
You can make it depend on ubuntu, so each time there is a new ubuntu version it will build again.

**Comment by czerwingithub** [comment]
Hello... thanks for pointing this out.  That docker image is for our old deprecated docker support.  No one really should be using it anymore.  We have marked it as such on our website's documentation, but not as well on hub.docker.  I'll take care of that in the next few days.

**Comment by pierreozoux** [comment]
Ah yes, I see what you mean.

Yes, maybe warn users or delete the repo.
