### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by jsanchezs** [scalyr/scalyr-agent-2#51]
I'm installing scalyr-agent-2 with `sudo bash /tmp/install-scalyr-agent-2.sh --set-api-key "KEY"       --start-agent`, but at some time, it fails with:
```
(Noting disappearance of scalyr-repo-bootstrap, which has been completely replaced.)
Setting up scalyr-agent-2 (2.0.27) ...
  File "/etc/init.d/scalyr-agent-2", line 193
    print 'The Scalyr Agent 2 version is %s' % SCALYR_VERSION
                                           ^
SyntaxError: Missing parentheses in call to 'print'
dpkg: error processing package scalyr-agent-2 (--configure):
 subprocess installed post-installation script returned error exit status 1
```

That's because I just have python3 installed on my machine (if you run `python`, you run `python3`)

Could the agent be compatible with python 3?

Thanks

**Comment by czerwingithub** [comment]
Thanks for reaching out.  Unfortunately, supporting python 3 is actually a pretty large project and not something we have planned in the near future.  Many of our customers rely on us supporting Python 2 (even some requiring Python 2.4).  My apologies for that, but I don't think there's any short cut for us to support both right now.

Do you have the ability to also install Python 2 on your machine?  We could look into making the agent better at using Python 2 vs Python 3 if both are installed on the machine.

**Comment by jsanchezs** [comment]
Thanks for the fast response. Migrating from 2 to 3 or making everything compatible between both has to be hard, so I completely understand you.

Yeah, i'm able to install Python 2, I opened the ticket in order to avoid installing it. Anyway, problem solved, so I close the ticket.

Thanks again for the info!
