### ISSUE TITLE
Upgrading from scalyr-agent-docker-syslog 2.0.50 to 2.1.5 is causing agent_status/agent_requests lines to be duplicated to stdout

### ISSUE THREAD

**Issue by ju2wheels** [scalyr/scalyr-agent-2#589]
As above, after upgrading from 2.0.50 to 2.1.5, the Docker containers are now logging agent_status and agent_requests to stdout when they werent before. Previously, these lines were only forwarded internally from the agent directly to scalyr, but now that they are going to stdout, we are getting them duplicated in scalyr and increasing our logs by almost 1GB for our fleet since we send the Docker container output first to local syslog (so we have a local copy) and then syslog forwards it to the scalyr syslog agent we have enabled to send it to scalyr.

Is there any way we can disable these lines from going to stdout without having to disable capturing the container output altogether in case something else important is logged?

**Comment by weilliu** [comment]
@ju2wheels I sent you an email last week and gave you the workaround solution with discard rule for filtering out all Scalyr agent logs. 
https://app.scalyr.com/help/parsing-logs#discard

It appears that you haven't applied the change yet. We recommend you make the changes as soon as you can, so you don't get duplicated agent logs in your account.

**Comment by weilliu** [comment]
I just replied to your email and added more context on why this change was implemented lately. Upgrading to the latest agent version + setting environment variable `SCALYR_STDOUT_SEVERITY` to ERROR in the config should disable stdout agent log.

**Comment by ju2wheels** [comment]
Closing, all set now, we are in the process of deploying the fix.

Thanks,
