### ISSUE TITLE
Kubernetes monitor requires nodes/proxy authorization

### ISSUE THREAD

**Issue by mgreensmith** [scalyr/scalyr-agent-2#631]
Greetings, I've discovered that the kubernetes monitor can't connect to the local kubelet API `/pods` endpoint for me unless I add an additional rule of `verb=get, resource=nodes, subresource=proxy` to the `scalyr-clusterrole` ClusterRole resource. I'm running k8s 1.17 on EKS.

Without `nodes/proxy` alongside the existing `node/stats` [permission](https://github.com/scalyr/scalyr-agent-2/blob/master/k8s/scalyr-service-account.yaml#L29), the kubelet `/pods` endpoint returns a `403`. The [official docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/#kubelet-authorization) concur that this permission is required.

Additionally, this rabbit hole was a deep one because the scalyr agent log output about this failure is suppressed (debug only), and it doesn't log anything to `agent.log` until it attempts (and fails) to connect to the hardcoded `_fallback_kubelet_url`  on port `10255`. It was frustrating to debug this, because no matter which kubelet-related config vars I changed (cert paths, template URIs, etc), it kept telling me that it couldn't connect to the fallback URI, and gave me no information about the failures to the primary kubelet URI. Maybe you could log [this failure](https://github.com/scalyr/scalyr-agent-2/blob/c89ab9dcba6d772313c09dbd897cdb102bc0236f/scalyr_agent/monitor_utils/k8s.py#L2376) at INFO instead?

Thanks!

**Comment by weilliu** [comment]
@mgreensmith I couldn't reproduce the issue on my end. I just sent you an email with additional information on how I deploy the agent and verify it. Let me know if you have any questions.

**Comment by Kami** [comment]
@mgreensmith I'm looking into it this, but I'm also having troubles reproducing it.

Can you please provide any additional information or custom cluster configuration which may help us to reproduce this issue?

Having said that - I agree that the current user-experience when hitting an error is not the best so I made the change you suggested above - #633. Now we log those errors under warning log level and also include a response body.
