### ISSUE TITLE
k8s scalyr agent, use python3 base image.

### ISSUE THREAD

**Issue by zkanda** [scalyr/scalyr-agent-2#740]
Hi Scalyr Team,

All the [scalyr image](https://github.com/scalyr/scalyr-agent-2/tree/master/docker) are still using python2 in k8s agent, I don't any reason not to upgrade since py3 has been supported for some time.

Thanks.

**Comment by weilliu** [comment]
@zkanda  Thanks for letting us know. I've asked engineering to get more info on this. We do agree with you that updating the images to Python 3 is something we should do, and yet we don't think running the agent under Python 3 results in any meaningful performance improvement or new capability to the Scalyr agent users today. 

I just created an internal ticket to track this task. We'll be updating the image when the team has the time to get around it. Please feel free to let us know if you have any other questions or concerns.

**Comment by ecktom** [comment]
Might also be worth to consider running some minimal image in the main stage, eg. Google's distroless `gcr.io/distroless/python3`

See also: 
https://github.com/GoogleContainerTools/distroless/blob/main/experimental/python3/README.md
https://github.com/GoogleContainerTools/distroless/blob/main/examples/python3/Dockerfile

**Comment by ecktom** [comment]
Hi @weilliu, Python 2 had it's EOL about 1 1/2 years ago which opens up some security concerns when running the container on every node... Is there any chance to speed this up?

**Comment by weilliu** [comment]
@ecktom Let me check with the team and get back to you next week. Apologies for the delay.

**Comment by weilliu** [comment]
Hi @ecktom the team just confirmed that Python 2 will be retired within the next couple of months. The tentative plan is to adopt Python 3 for the Docker image before making it a default for the Scalyr K8 Agent. We'll keep this issue open and inform you once the rollout completes.

**Comment by Kami** [comment]
@zkanda I just wanted to let you know that the latest Docker images now utilize Python 3.8.

In addition to that we now also offer smaller Alpine Linux based images - https://github.com/scalyr/scalyr-agent-2/blob/master/CHANGELOG.md#2126-yavin---jan-12-2022.
