### ISSUE TITLE
CronJobs

### ISSUE THREAD

**Issue by jsanchezs** [scalyr/scalyr-agent-2#84]
We are using Kubernetes [Cronjobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) in order to run a simple script each minute, but we have some troubles:

- We are not receiving all logs. Here you can see an example https://cl.ly/0O033C2X2g3H The cronjob is running each minute. We also add a 30 second sleep to give Scalyr some time to reach the logs. The cronjobs are running correctly at the same hour and if we check the pod logs (`kubectl logs POD`), we can see that the log is fine, but it is not in Scalyr.

- Parser doesn't change. We defined in the jobtemplate of the cronjob that we want a json parser. We can also describe the pods (`kubectl describe pod POD`) and there we can find that there is "parser=json", but in Scalyr, logs are with "parser=docker".

I suppose this is an issue with the cronjobs, because logs in the pods that we run through deployments are sent to Scalyr and it works perfectly, they are also parsed correctly. Congrats for this =D

**Comment by czerwingithub** [comment]
Hello -

Thanks for reporting this and sorry for the delay in response.  We are
going to have an engineer take a look into this, but we might not have a
follow up for you until next week.

thanks,
Steven

**Comment by echee2** [comment]
Hello @jsanchezs .  I know it's been a while but I just want to follow up:  AFAIK the issues you were facing were resolved a while back but this Issue wasn't updated. Please feel free to open a new Issue if you have any other problems. Thank you.
