### ISSUE TITLE
Weird tag number?

### ISSUE THREAD

**Issue by allwinpb** [scalyr/scalyr-agent-2#98]
https://github.com/scalyr/scalyr-agent-2/releases

Horta appears to be 2.0.23 but it looks like it should've been 2.0.32 going by past releases.
![screen shot 2018-06-18 at 11 23 52 pm](https://user-images.githubusercontent.com/4397532/41545856-b8d685b2-734e-11e8-947b-1f813100cc3b.png)

**Comment by czerwingithub** [comment]
Thanks for pointing this out.  This has been fixed now.
